projects:
  pawkit:
    schemaPath: amplify/backend/api/pawkit/schema.json
    includes:
      - api/graphql/**/*.ts
    excludes:
      - api/graphql/API.ts
      - api/*.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: api/graphql/API.ts
        docsFilePath: graphql
        frontend: javascript
        framework: react-native
extensions:
  amplify:
    version: 3
