projects:
  pawkit:
    schemaPath: amplify/backend/api/pawkit/schema.json
    includes:
      - graphql/**/*.ts
    excludes:
      - graphql/API.ts
      - graphql/api/*.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: graphql/API.ts
        docsFilePath: graphql
        frontend: javascript
        framework: react-native
extensions:
  amplify:
    version: 3
