/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-southeast-1",
  aws_cognito_identity_pool_id:
    "ap-southeast-1:d0159b6b-3eed-4e6c-acb3-bcd8bad63a2a",
  aws_cognito_region: "ap-southeast-1",
  aws_user_pools_id: "ap-southeast-1_KwVJoz3PW",
  aws_user_pools_web_client_id: "3apd1akedvjde05d9v4nbepre3",
  oauth: {
    domain: "pawkit-staging.auth.ap-southeast-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "exp://pawkit.exp.direct:/redirect/",
    redirectSignOut: "exp://pawkit.exp.direct:/signout/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: ["PHONE_NUMBER"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [],
  aws_cognito_mfa_configuration: "ON",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["PHONE_NUMBER"],
  aws_cloud_logic_custom: [
    {
      name: "AdminQueries",
      endpoint:
        "https://pfw2yx41zl.execute-api.ap-southeast-1.amazonaws.com/staging",
      region: "ap-southeast-1",
    },
    {
      name: "payments",
      endpoint:
        "https://xvw4s1t01g.execute-api.ap-southeast-1.amazonaws.com/staging",
      region: "ap-southeast-1",
    },
  ],
  aws_appsync_graphqlEndpoint:
    "https://gnecv3kjo5hfbesrnflggmc4by.appsync-api.ap-southeast-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-southeast-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-e6wjp25vrzfgxbn6czogbtkspq",
  aws_user_files_s3_bucket: "pawkitappcontent152309-staging",
  aws_user_files_s3_bucket_region: "ap-southeast-1",
};

export default awsmobile;
