/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://s0baxnvb85.execute-api.ap-southeast-1.amazonaws.com/production",
            "region": "ap-southeast-1"
        },
        {
            "name": "payments",
            "endpoint": "https://07i607lu20.execute-api.ap-southeast-1.amazonaws.com/production",
            "region": "ap-southeast-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://z5a6nb4xcnfu5o5o7ejnxspgve.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-hpjrps32sjdofgpswzsdxz3vou",
    "aws_cognito_identity_pool_id": "ap-southeast-1:7ecbd0f0-7f6d-4aee-89e4-c4534308a383",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_yDeQ6WWT5",
    "aws_user_pools_web_client_id": "14lipm1180ipb9923dcu5ssige",
    "oauth": {
        "domain": "pawkit-production.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://pawkit.exp.direct:/redirect/",
        "redirectSignOut": "exp://pawkit.exp.direct:/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "ON",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_user_files_s3_bucket": "pawkitappcontent89450-production",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
